"""add flashcards table

Revision ID: 274816b0d5ec
Revises: 419619149308
Create Date: 2025-12-19 14:57:32.619917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274816b0d5ec'
down_revision = '419619149308'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
