"""add flashcards table

Revision ID: 419619149308
Revises: add_hashed_password_users
Create Date: 2025-12-19 14:39:43.440470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '419619149308'
down_revision = 'add_hashed_password_users'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('flashcards', sa.Column('difficulty', sa.String(length=20), nullable=True))
    op.add_column('flashcards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('flashcards', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('flashcards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_flashcards_id'), 'flashcards', ['id'], unique=False)
    op.drop_column('flashcards', 'next_review')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('next_review', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_flashcards_id'), table_name='flashcards')
    op.alter_column('flashcards', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('flashcards', 'is_active')
    op.drop_column('flashcards', 'updated_at')
    op.drop_column('flashcards', 'difficulty')
    op.drop_column('flashcards', 'category')
    # ### end Alembic commands ###
