"""add_sm2_fields

Revision ID: a6b7dacb2d3d
Revises: d9f3ea806541
Create Date: 2025-12-20 03:22:12.200269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b7dacb2d3d'
down_revision = 'd9f3ea806541'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('repetitions', sa.Integer(), nullable=True))
    op.add_column('flashcards', sa.Column('easiness_factor', sa.Float(), nullable=True))
    op.add_column('flashcards', sa.Column('interval', sa.Integer(), nullable=True))
    op.add_column('flashcards', sa.Column('next_review', sa.DateTime(), nullable=True))
    op.add_column('flashcards', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'last_reviewed')
    op.drop_column('flashcards', 'next_review')
    op.drop_column('flashcards', 'interval')
    op.drop_column('flashcards', 'easiness_factor')
    op.drop_column('flashcards', 'repetitions')
    # ### end Alembic commands ###
